# Generated by Django 6.0.7 on 2026-08-09 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_encryptedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE_USER', 'Approved User'), ('REJECT_USER', 'Rejected User'), ('ACTIVATE_USER', 'Activated User'), ('DEACTIVATE_USER', 'Deactivated User'), ('DOWNLOAD_FILE', 'Downloaded File'), ('DELETE_FILE', 'Deleted File')], max_length=30)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
