# Generated by Django 6.0.7 on 2026-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
