# Generated by Django 6.0.7 on 2026-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminactivitylog_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactivitylog',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='adminactivitylog',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
