# Generated by Django 6.0.7 on 2026-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
