# Generated by Django 6.0.7 on 2026-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file_expiry_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
